CREATE GLOBAL TEMPORARY TABLE ofTmpStatus
(
    roomID        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roomJID       VARCHAR2(1024) NOT NULL,
    roomDestroyed NUMBER(1)      DEFAULT 0
);

INSERT INTO ofTmpStatus (roomJID)
SELECT DISTINCT room
FROM ofConversation;

UPDATE ofTmpStatus
SET roomDestroyed = 1
WHERE roomJID NOT IN (SELECT ofMucRoom.name || '@' || ofMucService.subdomain || '.' || ofProperty.propValue
                      FROM ofMucRoom
                               JOIN ofMucService ON ofMucRoom.serviceID = ofMucService.serviceID
                               CROSS JOIN ofProperty
                      WHERE ofProperty.name = 'xmpp.domain');

CREATE TABLE ofMucRoomStatus
(
    roomID        INTEGER PRIMARY KEY,
    roomJID       VARCHAR2(1024) NOT NULL,
    roomDestroyed NUMBER(1)      DEFAULT 0
);

INSERT INTO ofMucRoomStatus (SELECT * FROM ofTmpStatus);
INSERT INTO ofID (idType, id)
SELECT 655, MAX(roomID) + 1
FROM ofMucRoomStatus;
DROP TABLE ofTmpStatus;

ALTER TABLE ofConversation ADD roomID INTEGER DEFAULT -1 NOT NULL;
CREATE INDEX ofConversation_room_idx ON ofConversation (roomID);

MERGE INTO ofConversation c
    USING ofMucRoomStatus s ON (c.room = s.roomJID)
    WHEN MATCHED THEN UPDATE SET c.roomID = s.roomID;

-- Update database version
UPDATE ofVersion SET version = 9 WHERE name = 'monitoring';
