/*
 * Copyright (C) 2026 Ignite Realtime Foundation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jivesoftware.openfire.archive;

import org.dom4j.Element;
import org.dom4j.QName;
import org.jivesoftware.openfire.XMPPServer;
import org.jivesoftware.util.JiveGlobals;
import org.jivesoftware.util.SystemProperty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.xmpp.packet.JID;
import org.xmpp.packet.Message;

import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;
import java.util.function.Predicate;

/**
 * Utility methods that add XEP-0359 'Unique and Stable Stanza IDs' to one-to-one messages that are stored in a message
 * archive.
 *
 * Openfire adds such identifiers to messages that are exchanged in a chat room, but not to one-to-one messages. Without
 * such an identifier, the archive cannot provide clients with stable identifiers for one-to-one messages (which,
 * historically, caused this implementation to expose database identifiers to clients instead).
 *
 * An identifier is scoped to the entity that generated it (expressed in the 'by' attribute of the element). As a
 * one-to-one message is part of the archive of both participants of the conversation, two identifiers are needed: one
 * for each archive. To prevent one participant from learning the identifier that is used in the archive of the other
 * participant, these identifiers are treated differently:
 *
 * <ul>
 *     <li>The identifier for the archive of a <em>local recipient</em> is added to the stanza before it is routed. This
 *         allows the recipient to correlate the message that is delivered to it with the message in its archive.</li>
 *     <li>The identifier for the archive of a <em>local sender</em> is added to the representation of the stanza that
 *         is stored in the archive only. It is never transmitted with the routed stanza.</li>
 *     <li>When a message is retrieved from an archive, all identifiers that were generated for other local users are
 *         removed from the stanza (see {@link #filterForArchiveOwner(Element, JID)}).</li>
 *     <li>When a stanza is delivered to a local user, the identifiers that were generated for other local users are
 *         adjusted, in the stanza itself as well as in every stanza that it forwards (as is the case for a Message
 *         Carbons copy of a stanza that was sent by another resource of that user). When the user that the stanza is
 *         delivered to is a participant of the conversation that such a stanza is part of, the identifier is not
 *         removed, but is attributed to that user instead: it is the identifier that is used in its own archive. Such
 *         an adjustment is applied only to the stanzas that this server generated for the account of that user: an
 *         identifier in a stanza that a client provided was not generated by this implementation, and is removed
 *         rather than attributed to anyone. See {@link #adjustForRecipient(Message, JID)}.</li>
 *     <li>Any 'stanza-id' element that claims to be generated by a local user is removed from every message that is
 *         received by this server, as required by XEP-0359, even when no identifier is added (see
 *         {@link #removeSpoofedStanzaIDs(Message)}).</li>
 * </ul>
 *
 * An element of which the 'by' attribute value cannot be parsed as a JID is removed wherever this implementation
 * evaluates such elements: this server cannot determine whether it generated such an element, and can therefore not
 * vouch for it.
 *
 * The same identifier <em>value</em> is used in the archive of both participants of a one-to-one conversation. Each
 * participant only ever sees that value attributed to its own archive, and can use it to address the message in its own
 * archive. This allows the identifier that is used in the archive of the sender of a message to be included in the
 * Message Carbons copy of that message that is delivered to the other resources of that sender, without requiring the
 * server to retain state for the messages that it routes.
 *
 * A stanza that is addressed to an entity that is not a local user never obtains an identifier at all: this
 * implementation has no authority to generate an identifier on behalf of such an entity, and adding one to the routed
 * stanza would transmit it to an entity that has no business knowing it. As a consequence, the Message Carbons 'sent'
 * copy of such a message does not carry the identifier that is used in the archive of its (local) sender either: that
 * copy is generated (by Openfire core) from the stanza that was handed off for routing, before this implementation gets
 * a chance to archive it and mint an identifier for it. Deriving that identifier from the content of the stanza instead
 * (so that it could be recreated for the Carbons copy) was tried, but was abandoned: without any server-side state to
 * guarantee uniqueness, a client that deliberately resends the same body with the same 'id' attribute would obtain the
 * very same identifier for two distinct archived messages, which violates the 'unique in the archive' guarantee of
 * XEP-0359. Every identifier that this implementation generates is therefore an unconditionally random value.
 *
 * No identifiers are generated for entities that are not local users: this implementation has no authority to generate
 * identifiers on their behalf (and does not archive on their behalf either).
 *
 * @see <a href="https://xmpp.org/extensions/xep-0359.html">XEP-0359</a>
 */
public class ArchiveStanzaIDUtil
{
    private static final Logger Log = LoggerFactory.getLogger( ArchiveStanzaIDUtil.class );

    private static final QName STANZA_ID = QName.get( "stanza-id", "urn:xmpp:sid:0" );

    private static final QName FORWARDED = QName.get( "forwarded", "urn:xmpp:forward:0" );

    /**
     * Controls if this plugin generates XEP-0359 'Unique and Stable Stanza IDs' for one-to-one messages that it archives.
     *
     * When disabled, the archive falls back to using database identifiers, which is the behavior of versions of this
     * plugin that predate the introduction of this functionality.
     */
    public static final SystemProperty<Boolean> STANZA_ID_ENABLED = SystemProperty.Builder.ofType(Boolean.class)
        .setKey("conversation.stanzaID.enabled")
        .setDefaultValue(true)
        .setDynamic(true)
        .build();

    /**
     * The test that is used to determine if an entity is an account that is registered with this server. Package
     * visible alternatives of the methods in this class allow this to be substituted, to facilitate testing.
     */
    private static final Predicate<JID> DEFAULT_LOCAL_USER_TEST = ArchiveStanzaIDUtil::isLocalUser;

    /**
     * The maximum nesting depth of forwarded stanzas that is processed.
     *
     * Regular use of stanza forwarding (Message Carbons, archive query results) nests a stanza one or two levels deep.
     * A stanza that nests deeper is not processed: identifiers that it holds are neither adjusted nor removed. This
     * bounds the recursion that is applied to a stanza of which the structure is, ultimately, provided by a client.
     */
    private static final int MAX_FORWARDING_DEPTH = 10;

    private ArchiveStanzaIDUtil() {}

    /**
     * Returns true if this implementation should generate XEP-0359 identifiers.
     *
     * Apart from the plugin-specific configuration, the configuration that Openfire itself uses to generate stanza IDs
     * is honored.
     *
     * @return true if stanza IDs are to be generated, otherwise false.
     */
    public static boolean isEnabled()
    {
        return STANZA_ID_ENABLED.getValue()
            && JiveGlobals.getBooleanProperty( "xmpp.sid.enabled", true )
            && JiveGlobals.getBooleanProperty( "xmpp.sid.message.enabled", true );
    }

    /**
     * Returns true if the provided JID represents an account that is registered with (a domain of) this server.
     *
     * Only for such entities does this implementation generate stanza IDs.
     *
     * @param jid The address to evaluate (can be null).
     * @return true if the address is that of a local user account, otherwise false.
     */
    public static boolean isLocalUser( final JID jid )
    {
        if ( jid == null || jid.getNode() == null ) {
            return false;
        }
        return XMPPServer.getInstance().isLocal( jid );
    }

    /**
     * Adds a XEP-0359 'stanza-id' element for the provided archive owner to the stanza that is being routed.
     *
     * As required by XEP-0359, any pre-existing 'stanza-id' element that claims to be generated by a local user is
     * removed (irrespective of the archive owner that is provided): this implementation is the only entity that is
     * allowed to generate those. Identifiers that were generated by other entities (such as a chat room, or a remote
     * server) are retained.
     *
     * Unlike {@link #getArchivableStanzaXml(Message, JID...)}, this method modifies the stanza that is provided as an
     * argument (which is the point: the recipient of the stanza is to receive the identifier that is used in its
     * archive).
     *
     * @param message The stanza that is being routed (cannot be null).
     * @param archiveOwner The owner of the archive that the stanza will be stored in (cannot be null).
     * @return The identifier that was added, or null if no identifier was added.
     */
    public static String addStanzaIDToRoutedStanza( final Message message, final JID archiveOwner )
    {
        return addStanzaIDToRoutedStanza( message, archiveOwner, DEFAULT_LOCAL_USER_TEST );
    }

    /**
     * Adds a XEP-0359 'stanza-id' element for the provided archive owner to the stanza that is being routed, using the
     * provided test to determine if an entity is an account that is registered with this server.
     *
     * @param message The stanza that is being routed (cannot be null).
     * @param archiveOwner The owner of the archive that the stanza will be stored in (cannot be null).
     * @param localUserTest Test that determines if an entity is a local user (cannot be null).
     * @return The identifier that was added, or null if no identifier was added.
     * @see #addStanzaIDToRoutedStanza(Message, JID)
     */
    static String addStanzaIDToRoutedStanza( final Message message, final JID archiveOwner, final Predicate<JID> localUserTest )
    {
        if ( message == null ) {
            throw new IllegalArgumentException( "Argument 'message' cannot be null." );
        }
        if ( archiveOwner == null ) {
            throw new IllegalArgumentException( "Argument 'archiveOwner' cannot be null." );
        }

        try {
            if ( !isEnabled() ) {
                return null;
            }

            final Element parentElement = message.getElement();
            removeStanzaIDsOfLocalUsers( parentElement, message, localUserTest );

            if ( !localUserTest.test( archiveOwner ) ) {
                return null;
            }

            final String id = UUID.randomUUID().toString();
            addStanzaID( parentElement, id, archiveOwner.toBareJID() );
            Log.debug( "Added stanza ID '{}' (by '{}') to a stanza that is being routed.", id, archiveOwner.toBareJID() );
            return id;
        } catch ( Exception e ) {
            Log.warn( "An exception occurred while adding a stable and unique stanza ID to a message that is being routed. The message will be processed without such an ID.", e );
            return null;
        }
    }

    /**
     * Removes all XEP-0359 'stanza-id' elements that claim to have been generated by an account that is registered with
     * this server. Only this implementation is allowed to generate those.
     *
     * XEP-0359 requires an entity to remove an element of which the 'by' attribute value matches the value that it
     * would itself set, even when it adds no identifier of its own. This method is therefore to be invoked for every
     * message that is received by this server, irrespective of whether that message is archived, and irrespective of
     * the configuration that controls the generation of identifiers by this implementation.
     *
     * Only elements that are a direct child of the stanza are evaluated: this method is invoked for a stanza that this
     * server receives, and a stanza that such a stanza forwards (as used by, amongst others, Message Carbons and MAM
     * results) can legitimately hold elements that refer to a local user. Forwarded stanzas are evaluated when a stanza
     * is delivered instead, by {@link #adjustForRecipient(Message, JID)}, which has the context needed to tell a stanza
     * that this server generated from one that a client provided.
     *
     * @param message The stanza that is being routed (cannot be null).
     * @return true if at least one element was removed, otherwise false.
     */
    public static boolean removeSpoofedStanzaIDs( final Message message )
    {
        return removeSpoofedStanzaIDs( message, DEFAULT_LOCAL_USER_TEST );
    }

    /**
     * Removes all XEP-0359 'stanza-id' elements that claim to have been generated by an account that is registered with
     * this server, using the provided test to determine if an entity is such an account.
     *
     * @param message The stanza that is being routed (cannot be null).
     * @param localUserTest Test that determines if an entity is a local user (cannot be null).
     * @return true if at least one element was removed, otherwise false.
     * @see #removeSpoofedStanzaIDs(Message)
     */
    static boolean removeSpoofedStanzaIDs( final Message message, final Predicate<JID> localUserTest )
    {
        if ( message == null ) {
            throw new IllegalArgumentException( "Argument 'message' cannot be null." );
        }

        try {
            return removeStanzaIDsOfLocalUsers( message.getElement(), message, localUserTest );
        } catch ( Exception e ) {
            Log.warn( "An exception occurred while removing spoofed stanza IDs from a message that is being routed. The message will be processed as-is.", e );
            return false;
        }
    }

    /**
     * Returns the XML representation of a stanza, as it should be stored in the message archive of the provided
     * owners.
     *
     * A one-to-one message is stored only once, but is part of the archive of both participants of the conversation.
     * As XEP-0359 identifiers are scoped by the entity that generated them, a 'stanza-id' element is present for each
     * of the provided archive owners (that is a local user). The same identifier value is used for each of them, as
     * each participant only ever sees the element that is attributed to itself.
     *
     * When the stanza already contains an identifier for one of the archive owners (which is the case for the recipient
     * of the stanza, for which the identifier was added before the stanza was routed, by
     * {@link #addStanzaIDToRoutedStanza(Message, JID)}), the value of that identifier is reused.
     *
     * The stanza that is provided in the argument is not modified: the identifiers are added to a copy of that stanza.
     *
     * @param message The stanza to be archived (cannot be null).
     * @param archiveOwners The owners of the archives that the stanza will be stored in (cannot be null).
     * @return The XML representation of the stanza to be stored in the archive.
     */
    public static String getArchivableStanzaXml( final Message message, final JID... archiveOwners )
    {
        return getArchivableStanzaXml( message, DEFAULT_LOCAL_USER_TEST, archiveOwners );
    }

    /**
     * Returns the XML representation of a stanza, as it should be stored in the message archive of the provided
     * owners, using the provided test to determine if an entity is an account that is registered with this server.
     *
     * @param message The stanza to be archived (cannot be null).
     * @param localUserTest Test that determines if an entity is a local user (cannot be null).
     * @param archiveOwners The owners of the archives that the stanza will be stored in.
     * @return The XML representation of the stanza to be stored in the archive.
     * @see #getArchivableStanzaXml(Message, JID...)
     */
    static String getArchivableStanzaXml( final Message message, final Predicate<JID> localUserTest, final JID... archiveOwners )
    {
        if ( message == null ) {
            throw new IllegalArgumentException( "Argument 'message' cannot be null." );
        }

        try {
            if ( !isEnabled() ) {
                return message.toXML();
            }

            // Deduplicate (a user can send a message to itself) while maintaining a predictable order. Only local users
            // have an archive that is maintained by this implementation.
            final Set<String> owners = new LinkedHashSet<>();
            if (archiveOwners != null) {
                for ( final JID archiveOwner : archiveOwners ) {
                    if ( localUserTest.test( archiveOwner ) ) {
                        owners.add( archiveOwner.toBareJID() );
                    }
                }
            }

            if ( owners.isEmpty() ) {
                return message.toXML();
            }

            // Do not modify the stanza that is being routed: only the archived representation is enriched.
            final Message copy = message.createCopy();
            final Element parentElement = copy.getElement();

            // The same value is used for all archive owners. When the stanza already holds an identifier for one of
            // them (typically the recipient, for which an identifier was added before the stanza was routed), that
            // value is reused. This allows every party to address the message in its own archive using the value that
            // it received, without any party having to learn a value that is used by another party.
            String id = null;
            for ( final String owner : owners ) {
                id = findStanzaID( parentElement, owner );
                if ( id != null ) {
                    break;
                }
            }
            if ( id == null ) {
                // No identifier was added before the stanza was routed, which is the case when the stanza is addressed
                // to an entity that is not a local user. A fresh, random identifier is used instead: unlike a value
                // derived from the content of the stanza, this guarantees uniqueness even when a client resends a
                // stanza with the same 'id' attribute and body, at the cost of that identifier not being obtainable by
                // the Message Carbons 'sent' copy of such a message (that copy is generated before the stanza is
                // archived, from the stanza that was handed off for routing, which never holds this identifier).
                id = UUID.randomUUID().toString();
            }

            for ( final String owner : owners ) {
                if ( findStanzaID( parentElement, owner ) != null ) {
                    // An identifier for this archive owner was already added (before the stanza was routed).
                    continue;
                }
                addStanzaID( parentElement, id, owner );
            }

            return copy.toXML();
        } catch ( Exception e ) {
            Log.warn( "An exception occurred while adding stable and unique stanza IDs to a message that is to be archived. The message will be archived without such IDs.", e );
            return message.toXML();
        }
    }

    /**
     * Removes all XEP-0359 'stanza-id' elements that were generated for local users other than the provided archive
     * owner.
     *
     * A one-to-one message is stored in the archive only once, even though it is part of the archive of both
     * participants of the conversation. The archived representation therefore holds an identifier for each of them.
     * A participant should not learn the identifier that is used in the archive of the other participant, which is why
     * those are removed when a message is retrieved from the archive.
     *
     * Identifiers that were generated by entities that are not local users (such as chat rooms, or remote servers) are
     * retained.
     *
     * @param stanzaElement The element that represents the stanza that is retrieved from the archive (cannot be null).
     * @param archiveOwner The owner of the archive from which the stanza was retrieved (cannot be null).
     */
    public static void filterForArchiveOwner( final Element stanzaElement, final JID archiveOwner )
    {
        filterForArchiveOwner( stanzaElement, archiveOwner, DEFAULT_LOCAL_USER_TEST );
    }

    /**
     * Removes all XEP-0359 'stanza-id' elements that were generated for local users other than the provided archive
     * owner, using the provided test to determine if an entity is an account that is registered with this server.
     *
     * @param stanzaElement The element that represents the stanza that is retrieved from the archive (cannot be null).
     * @param archiveOwner The owner of the archive from which the stanza was retrieved (cannot be null).
     * @param localUserTest Test that determines if an entity is a local user (cannot be null).
     * @see #filterForArchiveOwner(Element, JID)
     */
    static void filterForArchiveOwner( final Element stanzaElement, final JID archiveOwner, final Predicate<JID> localUserTest )
    {
        if ( stanzaElement == null ) {
            throw new IllegalArgumentException( "Argument 'stanzaElement' cannot be null." );
        }
        if ( archiveOwner == null ) {
            throw new IllegalArgumentException( "Argument 'archiveOwner' cannot be null." );
        }

        try {
            removeStanzaIDsOfOtherLocalUsers( stanzaElement, archiveOwner.toBareJID(), localUserTest );
        } catch ( Exception e ) {
            Log.warn( "An exception occurred while removing stanza IDs of other users from a message that was retrieved from the archive of '{}'.", archiveOwner, e );
        }
    }

    /**
     * Prepares a stanza that is about to be delivered to a local user, by adjusting the XEP-0359 'stanza-id' elements
     * that were generated for other local users.
     *
     * Stanzas that are forwarded by the stanza that is being delivered are processed too. This is needed for Message
     * Carbons: the 'sent' copy that is delivered to the other resources of a sender is generated from the stanza that
     * was routed to the recipient of that stanza, and therefore holds an identifier that is attributed to that
     * recipient.
     *
     * When the user that the stanza is delivered to is a participant of the conversation that a (forwarded) stanza is
     * part of, then the identifier that is attributed to the other participant is re-attributed to that user: the same
     * value is used in the archives of both participants (see {@link #getArchivableStanzaXml(Message, JID...)}). This
     * is what allows the sender of a message to obtain the identifier of its own archive from the Message Carbons copy
     * of that message.
     *
     * Such an adjustment is applied only to the stanzas that this server generated for the account of the recipient. A
     * stanza that is forwarded by a stanza that a client provided holds identifiers that this implementation did not
     * generate; those are removed, never re-attributed.
     *
     * Identifiers that are attributed to any other local user are removed: a user should not learn the identifier that
     * is used in the archive of another user.
     *
     * Identifiers that were generated by entities that are not local users (such as chat rooms, or remote servers) are
     * retained, as are the identifiers that are already attributed to the user that the stanza is delivered to (notably
     * those in the results of a query of its own archive).
     *
     * A stanza that is addressed to an entity that is not a local user does not hold an identifier at all (as no
     * identifier is added to a stanza that is routed to such an entity). Such a stanza is therefore left as-is: the
     * Message Carbons 'sent' copy of such a message does not obtain the identifier that is used in the archive of its
     * (local) sender.
     *
     * This method returns without modifying the stanza when the generation of identifiers is disabled by configuration,
     * or when the stanza holds no identifier at all.
     *
     * @param message The stanza that is about to be delivered (cannot be null).
     * @param recipient The entity that the stanza is delivered to (cannot be null).
     * @return true if at least one element was modified or removed, otherwise false.
     */
    public static boolean adjustForRecipient( final Message message, final JID recipient )
    {
        return adjustForRecipient( message, recipient, DEFAULT_LOCAL_USER_TEST );
    }

    /**
     * Prepares a stanza that is about to be delivered to a local user, by adjusting the XEP-0359 'stanza-id' elements
     * that were generated for other local users, using the provided test to determine if an entity is an account that
     * is registered with this server.
     *
     * A stanza that is forwarded by a stanza that this server did not generate for the account of the recipient was
     * provided by a client. Identifiers in such a stanza are removed, never re-attributed.
     *
     * This method returns without modifying the stanza when the generation of identifiers is disabled by configuration,
     * or when the stanza holds no identifier at all.
     *
     * @param message The stanza that is about to be delivered (cannot be null).
     * @param recipient The entity that the stanza is delivered to (cannot be null).
     * @param localUserTest Test that determines if an entity is a local user (cannot be null).
     * @return true if at least one element was modified or removed, otherwise false.
     * @see #adjustForRecipient(Message, JID)
     */
    static boolean adjustForRecipient( final Message message, final JID recipient, final Predicate<JID> localUserTest )
    {
        if ( message == null ) {
            throw new IllegalArgumentException( "Argument 'message' cannot be null." );
        }
        if ( recipient == null ) {
            throw new IllegalArgumentException( "Argument 'recipient' cannot be null." );
        }

        try {
            if ( !isEnabled() ) {
                // No identifiers are being generated, so there are none of ours to adjust. Note that identifiers that
                // were generated while this was enabled are still present in stanzas that are retrieved from the
                // archive. Those are adjusted by the archive implementation itself (see #filterForArchiveOwner).
                return false;
            }

            if ( !hasStanzaID( message.getElement(), 0 ) ) {
                // Most stanzas hold no identifier at all. Avoid the more expensive processing below for those.
                return false;
            }

            if ( !localUserTest.test( recipient ) ) {
                // Identifiers of local users are not to be transmitted to entities that are not local users at all.
                // Such stanzas are not stamped by this implementation in the first place.
                return false;
            }

            return adjustRecursively( message.getElement(), recipient.toBareJID(), localUserTest, true, 0 );
        } catch ( Exception e ) {
            Log.warn( "An exception occurred while adjusting stanza IDs of a stanza that is delivered to '{}'.", recipient, e );
            return false;
        }
    }

    /**
     * Adjusts the XEP-0359 'stanza-id' elements that were generated for local users other than the provided owner in
     * the provided element, as well as in every stanza that is forwarded by it.
     *
     * A stanza is 'trusted' when it was generated by this server: the stanza that is being delivered, and every stanza
     * that is forwarded by a stanza that this server generated for the account of the owner (as is the case for a
     * Message Carbons copy, and for the result of a query of the archive of that account). Only in such a stanza can an
     * element that refers to a local user have been generated by this implementation.
     *
     * In any other stanza, an element that refers to a local user was provided by a client. Those are removed, rather
     * than adjusted: this server is not to deliver an identifier as if it had generated it.
     *
     * Stanzas that are nested deeper than {@link #MAX_FORWARDING_DEPTH} are left as-is.
     *
     * @param stanzaElement The element that represents a stanza (cannot be null).
     * @param owner The bare JID of the entity that the stanza is delivered to (cannot be null).
     * @param localUserTest Test that determines if an entity is a local user (cannot be null).
     * @param trusted Whether the stanza was generated by this server.
     * @param depth The nesting depth of the stanza that is being processed.
     * @return true if at least one element was modified or removed, otherwise false.
     */
    private static boolean adjustRecursively(final Element stanzaElement, final String owner, final Predicate<JID> localUserTest, final boolean trusted, final int depth)
    {
        boolean result;
        if ( trusted ) {
            result = adjustStanzaIDsOfOtherLocalUsers( stanzaElement, owner, localUserTest );
        } else {
            result = removeStanzaIDsOfLocalUsers( stanzaElement, null, localUserTest );
        }

        if (depth >= MAX_FORWARDING_DEPTH) {
            Log.debug("Not processing stanzas that are forwarded by a stanza that is delivered to '{}', as the maximum nesting depth of {} has been reached.", owner, MAX_FORWARDING_DEPTH);
            return result;
        }

        // Only a stanza that this server generated for the account of the owner can forward a stanza that holds
        // identifiers that this implementation generated.
        final boolean forwardedStanzasAreTrusted = trusted && isGeneratedForAccount( stanzaElement, owner );

        for ( final Element forwardedStanza : findForwardedStanzas( stanzaElement ) ) {
            result |= adjustRecursively(forwardedStanza, owner, localUserTest, forwardedStanzasAreTrusted, depth + 1);
        }
        return result;
    }

    /**
     * Returns true if the provided element represents a stanza that this server generated for the account of the
     * provided owner, such as a Message Carbons copy, or the result of a query of the archive of that account.
     *
     * Such a stanza is addressed from the bare JID of the account (as defined in XEP-0280), or has no addressee at all.
     * A stanza that is submitted by a client always has the full JID of that client as its 'from' attribute value, as
     * that value is provided by this server.
     *
     * @param stanzaElement The element that represents a stanza (cannot be null).
     * @param owner The bare JID of the entity that the stanza is delivered to (cannot be null).
     * @return true if the stanza was generated by this server for the account of the owner, otherwise false.
     */
    private static boolean isGeneratedForAccount( final Element stanzaElement, final String owner )
    {
        final String from = stanzaElement.attributeValue( "from" );
        if ( from == null || from.isEmpty() ) {
            return true;
        }
        try {
            final JID fromJid = new JID( from );
            return fromJid.getResource() == null && owner.equals( fromJid.toBareJID() );
        } catch ( IllegalArgumentException e ) {
            Log.debug( "Unable to parse the 'from' attribute value '{}' of a stanza as a JID.", from, e );
            return false;
        }
    }

    /**
     * Re-attributes the XEP-0359 'stanza-id' element of the other participant of the conversation that the provided
     * stanza is part of to the provided owner, and removes the elements that are attributed to any other local user.
     *
     * An element of which the 'by' attribute value cannot be parsed as a JID is removed: this implementation cannot
     * determine whether it generated such an element, and can therefore not vouch for it.
     *
     * @param stanzaElement The element that holds the 'stanza-id' elements (cannot be null).
     * @param owner The bare JID of the entity that the stanza is delivered to (cannot be null).
     * @param localUserTest Test that determines if an entity is a local user (cannot be null).
     * @return true if at least one element was modified or removed, otherwise false.
     */
    private static boolean adjustStanzaIDsOfOtherLocalUsers( final Element stanzaElement, final String owner, final Predicate<JID> localUserTest )
    {
        final boolean isParticipant = isParticipant( stanzaElement, owner );
        boolean hasIdForOwner = findStanzaID( stanzaElement, owner ) != null;

        boolean result = false;
        final Iterator<Element> iterator = stanzaElement.elementIterator( STANZA_ID );
        while ( iterator.hasNext() ) {
            final Element element = iterator.next();
            final String by = element.attributeValue( "by" );
            if ( by == null || owner.equals( by ) ) {
                continue;
            }

            final JID byJid;
            try {
                byJid = new JID( by );
            } catch ( IllegalArgumentException e ) {
                Log.debug( "Unable to parse the 'by' attribute value '{}' of a 'stanza-id' element as a JID. The malformed element is removed.", by, e );
                iterator.remove();
                result = true;
                continue;
            }

            if ( !localUserTest.test( byJid ) ) {
                continue;
            }

            final String id = element.attributeValue( "id" );
            if ( isParticipant && !hasIdForOwner && id != null && !id.isEmpty() ) {
                // The same value is used in the archive of both participants of the conversation. Attribute it to the
                // entity that the stanza is delivered to, which is the archive that it can use the value in.
                element.addAttribute( "by", owner );
                hasIdForOwner = true;
                Log.debug( "Attributed stanza ID '{}' to '{}' in a stanza that is delivered to it.", id, owner );
            } else {
                iterator.remove();
            }
            result = true;
        }
        return result;
    }

    /**
     * Returns true if the provided entity is the sender or the addressee of the stanza that is represented by the
     * provided element.
     *
     * @param stanzaElement The element that represents a stanza (cannot be null).
     * @param bareJid The bare JID of the entity to evaluate (cannot be null).
     * @return true if the entity is a participant of the conversation that the stanza is part of, otherwise false.
     */
    private static boolean isParticipant( final Element stanzaElement, final String bareJid )
    {
        for ( final String attributeName : new String[] { "from", "to" } ) {
            final String value = stanzaElement.attributeValue( attributeName );
            if ( value == null || value.isEmpty() ) {
                continue;
            }
            try {
                if ( bareJid.equals( new JID( value ).toBareJID() ) ) {
                    return true;
                }
            } catch ( IllegalArgumentException e ) {
                Log.debug( "Unable to parse the '{}' attribute value '{}' of a stanza as a JID.", attributeName, value, e );
            }
        }
        return false;
    }

    /**
     * Returns the elements that represent the stanzas that are forwarded by the provided element (as defined in
     * XEP-0297 'Stanza Forwarding', used by, amongst others, XEP-0280 'Message Carbons').
     *
     * Stanzas that are nested deeper than {@link #MAX_FORWARDING_DEPTH} are left as-is.
     *
     * @param element The element to inspect (cannot be null).
     * @return All forwarded stanzas (never null, possibly empty).
     */
    private static Set<Element> findForwardedStanzas( final Element element )
    {
        return findForwardedStanzas( element, 0 );
    }

    /**
     * Returns the elements that represent the stanzas that are forwarded by the provided element (as defined in
     * XEP-0297 'Stanza Forwarding', used by, amongst others, XEP-0280 'Message Carbons').
     *
     * Stanzas that are nested deeper than {@link #MAX_FORWARDING_DEPTH} are left as-is.
     *
     * @param element The element to inspect (cannot be null).
     * @param depth The nesting depth of the stanza that is being processed.
     * @return All forwarded stanzas (never null, possibly empty).
     */
    private static Set<Element> findForwardedStanzas( final Element element, final int depth )
    {
        final Set<Element> result = new LinkedHashSet<>();
        if ( depth >= MAX_FORWARDING_DEPTH ) {
            return result;
        }
        for ( final Element child : element.elements() ) {
            if ( FORWARDED.equals( child.getQName() ) ) {
                result.addAll( child.elements( "message" ) );
            } else if ( !STANZA_ID.equals( child.getQName() ) ) {
                result.addAll( findForwardedStanzas( child, depth + 1 ) );
            }
        }
        return result;
    }

    /**
     * Removes all XEP-0359 'stanza-id' elements that were generated for local users other than the provided owner.
     *
     * An element of which the 'by' attribute value cannot be parsed as a JID is removed: this implementation cannot
     * determine whether it generated such an element, and can therefore not vouch for it.
     *
     * @param stanzaElement The element that holds the 'stanza-id' elements (cannot be null).
     * @param owner The bare JID of the entity for which identifiers are to be retained (cannot be null).
     * @param localUserTest Test that determines if an entity is a local user (cannot be null).
     * @return true if at least one element was removed, otherwise false.
     */
    private static boolean removeStanzaIDsOfOtherLocalUsers( final Element stanzaElement, final String owner, final Predicate<JID> localUserTest )
    {
        boolean result = false;
        final Iterator<Element> iterator = stanzaElement.elementIterator( STANZA_ID );
        while ( iterator.hasNext() ) {
            final Element element = iterator.next();
            final String by = element.attributeValue( "by" );
            if ( by == null || owner.equals( by ) ) {
                continue;
            }

            final JID byJid;
            try {
                byJid = new JID( by );
            } catch ( IllegalArgumentException e ) {
                Log.debug( "Unable to parse the 'by' attribute value '{}' of a 'stanza-id' element as a JID. The malformed element is removed.", by, e );
                iterator.remove();
                result = true;
                continue;
            }

            if ( localUserTest.test( byJid ) ) {
                iterator.remove();
                result = true;
            }
        }
        return result;
    }

    /**
     * Removes all XEP-0359 'stanza-id' elements that claim to be generated by a local user. Only this implementation
     * is allowed to generate those.
     *
     * An element of which the 'by' attribute value cannot be parsed as a JID is removed as well: this implementation
     * cannot determine whether it generated such an element, and can therefore not vouch for it. An element that has no
     * 'by' attribute at all is left as-is (such an element is invalid, but it makes no claim that this implementation
     * needs to refute).
     *
     * Only elements that are a direct child of the provided element are evaluated.
     *
     * @param parentElement The element that holds the 'stanza-id' elements (cannot be null).
     * @param message The message that is being processed, used for logging purposes only (can be null).
     * @param localUserTest Test that determines if an entity is a local user (cannot be null).
     * @return true if at least one element was removed, otherwise false.
     */
    private static boolean removeStanzaIDsOfLocalUsers( final Element parentElement, final Message message, final Predicate<JID> localUserTest )
    {
        boolean result = false;
        final Iterator<Element> iterator = parentElement.elementIterator( STANZA_ID );
        while ( iterator.hasNext() ) {
            final Element element = iterator.next();
            final String by = element.attributeValue( "by" );
            if ( by == null ) {
                continue;
            }

            final JID byJid;
            try {
                byJid = new JID( by );
            } catch ( IllegalArgumentException e ) {
                Log.debug( "Unable to parse the 'by' attribute value '{}' of a 'stanza-id' element as a JID. The malformed element is removed.", by, e );
                iterator.remove();
                result = true;
                continue;
            }

            if ( localUserTest.test( byJid ) ) {
                Log.debug( "Removing a 'stanza-id' element (by='{}', id='{}') from a stanza (from='{}', to='{}'), as its 'by' attribute value matches the value that this implementation would set.",
                    by, element.attributeValue( "id" ), message == null ? null : message.getFrom(), message == null ? null : message.getTo() );
                iterator.remove();
                result = true;
            }
        }
        return result;
    }

    private static String findStanzaID( final Element parentElement, final String by )
    {
        for ( final Element element : parentElement.elements( STANZA_ID ) ) {
            if ( by.equals( element.attributeValue( "by" ) ) ) {
                final String id = element.attributeValue( "id" );
                if ( id != null && !id.isEmpty() ) {
                    return id;
                }
            }
        }
        return null;
    }

    private static void addStanzaID( final Element parentElement, final String id, final String by )
    {
        final Element stanzaIdElement = parentElement.addElement( STANZA_ID );
        stanzaIdElement.addAttribute( "id", id );
        stanzaIdElement.addAttribute( "by", by );
    }

    /**
     * Returns true if the provided element, or any element that it contains, is a XEP-0359 'stanza-id' element.
     *
     * This is a cheap test that allows the more expensive processing of a stanza to be skipped for the common case of
     * a stanza that holds no identifier at all. It traverses forwarded stanzas in exactly the way that
     * {@link #adjustRecursively(Element, String, Predicate, boolean, int)} does, so that it cannot conclude that a
     * stanza holds no identifier that that method would have reached.
     *
     * @param element The element to inspect (cannot be null).
     * @param depth The current nesting depth.
     * @return true if at least one 'stanza-id' element is present within the bounded depth, otherwise false.
     */
    private static boolean hasStanzaID( final Element element, final int depth )
    {
        if ( !element.elements( STANZA_ID ).isEmpty() ) {
            return true;
        }
        if ( depth >= MAX_FORWARDING_DEPTH ) {
            return false;
        }
        for ( final Element forwardedStanza : findForwardedStanzas( element ) ) {
            if ( hasStanzaID( forwardedStanza, depth + 1 ) ) {
                return true;
            }
        }
        return false;
    }
}
